# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTKTUFt9JzaWK3dNmV_lX-WM_nucqjuM
"""

import requests
import pandas as pd
import os
from datetime import datetime
from bs4 import BeautifulSoup

# 1. SETUP
url = "https://www.scrapethissite.com/pages/forms/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

teams_data = []
# Create a single timestamp for this specific scrape run
scrape_time = datetime.now().isoformat()

# 2. EXTRACTION & TRANSFORMATION
# Selecting 'tr.team' as found in the Hockey Scraper site
for row in soup.select("tr.team"):
    name = row.select_one(".name").get_text(strip=True)
    year = row.select_one(".year").get_text(strip=True)
    wins = int(row.select_one(".wins").get_text(strip=True))
    losses = int(row.select_one(".losses").get_text(strip=True))

    # Calculate Business Metric (KPI)
    win_rate = round((wins / (wins + losses)) * 100,
                     2) if (wins + losses) > 0 else 0

    # Append to list with the 'scraped_at' timestamp
    teams_data.append({
        "team_identity": name,
        "fiscal_year": year,
        "total_wins": wins,
        "total_losses": losses,
        "win_rate_pct": win_rate,
        "scraped_at": scrape_time  # ← Added for historical tracking
    })

# 3. CONVERT TO DATAFRAME
df = pd.DataFrame(teams_data)

# 4. SMART EXPORT (Append Logic)
filename = "hockey_historical_data.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
    print(f"✅ Data appended to {filename}")
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)
    print(f"✅ New file created: {filename}")

print(f"📊 Processed {len(df)} teams. Total rows now stored in local storage.")
print(df.head())


# 1. Target the data source
url = "https://www.scrapethissite.com/pages/forms/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

rows = []

# 2. Scrape and calculate business metrics
for team in soup.select("tr.team"):
    name = team.select_one(".name").get_text(strip=True)
    year = team.select_one(".year").get_text(strip=True)
    wins = int(team.select_one(".wins").get_text(strip=True))
    losses = int(team.select_one(".losses").get_text(strip=True))
    gf = int(team.select_one(".gf").get_text(strip=True))  # Goals For
    ga = int(team.select_one(".ga").get_text(strip=True))  # Goals Against

    # Logic: Win Percentage is a key KPI (Key Performance Indicator)
    win_pct = round((wins / (wins + losses)) * 100,
                    2) if (wins + losses) > 0 else 0

    rows.append({
        "Team_Name": name,
        "Season": year,
        "Wins": wins,
        "Losses": losses,
        "Win_Percentage": win_pct,
        "Goal_Difference": gf - ga
    })

# 3. Create DataFrame and Export to CSV
df = pd.DataFrame(rows)
df.to_csv("business_case_analysis.csv", index=False)

print("✅ DONE! The file 'business_case_analysis.csv' has been created.")


# 1. Adapt URL to the Hockey Business Case
url = "https://www.scrapethissite.com/pages/forms/"
response = requests.get(url, timeout=20)
response.encoding = "utf-8"
soup = BeautifulSoup(response.text, "html.parser")

rows = []

# 2. Adapt Selectors
# Container is the table row with class 'team'
for item in soup.select("tr.team"):

    # Extract the fields relevant to your business question
    name_el = item.select_one(".name")
    year_el = item.select_one(".year")
    wins_el = item.select_one(".wins")
    loss_el = item.select_one(".losses")

    # Clean the text
    team_name = name_el.get_text(strip=True) if name_el else None
    season = year_el.get_text(strip=True) if year_el else None
    wins = wins_el.get_text(strip=True) if wins_el else "0"
    losses = loss_el.get_text(strip=True) if loss_el else "0"

    # Business Logic: Convert strings to numbers for analysis
    rows.append({
        "Team_Name": team_name,
        "Season": season,
        "Wins": int(wins),
        "Losses": int(losses),
        # Calculate a KPI (Win Rate) for the business case
        "Win_Rate": round(int(wins) / (int(wins) + int(losses)), 2) if (int(wins) + int(losses)) > 0 else 0
    })

# 3. Create DataFrame
df = pd.DataFrame(rows)

# 4. Generate the CSV file for your report
df.to_csv("hockey_business_analysis.csv", index=False)

print("✅ CSV File Created: hockey_business_analysis.csv")
print(df.head())  # Preview the first 5 rows

# This gives you Mean, Max, Min, and Standard Deviation for all your numbers
df.describe()

# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")
df.head(3)

# Apply your cleaning logic to the Wins and Losses columns
# This ensures any hidden symbols or spaces are removed

# 1. Clean the 'Wins' column
df["Wins"] = (
    df["Wins"]
    # Convert to string to use .str methods
    .astype(str)
    .str.replace(r"[^0-9.]", "", regex=True)   # Keep ONLY digits and dots
    # Finally, turn it into a real number
    .astype(int)
)

# 2. Clean the 'Losses' column
df["Losses"] = (
    df["Losses"]
    .astype(str)
    .str.replace(r"[^0-9.]", "", regex=True)
    .astype(int)
)

print("✅ Cleaning Complete: Wins and Losses are now pure integers.")

# THE AUDIT CHECK
print("--- Data Integrity Check ---")
print(df.dtypes)  # Look for 'int64' or 'float64' next to your numbers

# Try a math operation to prove it's working
print(f"\nTotal Wins in Dataset: {df['Wins'].sum()}")

# 1. AUDIT: See how many missing values exist per column
print("--- Missing Values Audit ---")
print(df.isnull().sum())

# 2. REPAIR: Fill missing Team Names with "Unknown"
# This ensures every row has a label for your Bar Charts
df["Team_Name"] = df["Team_Name"].fillna("Unknown Team")

# 3. REPAIR: Fill missing Numeric values with 0
# If Wins or Losses are missing (NaN), we assume 0 so the math doesn't break
df["Wins"] = df["Wins"].fillna(0)
df["Losses"] = df["Losses"].fillna(0)

# 4. RE-CALCULATE: Fix Win_Rate if any numbers were missing
# (0 wins / 0 games) would cause an error, so we handle that logic here
df["Win_Rate"] = df["Win_Rate"].fillna(0)

print("\n✅ Data Cleaning Complete: No more NULL values in critical columns.")

# 1. Rename columns to follow professional business standards
df = df.rename(columns={
    "Team_Name": "team_identity",      # The full official name
    "Season": "fiscal_year",           # Clarify this is a time-period
    "Wins": "total_wins",              # Explicitly state it's a total
    "Losses": "total_losses",          # Explicitly state it's a total
    "Win_Rate": "win_performance_kpi"  # Highlight this as a Key Performance Indicator
})

# 2. Verify the changes
print("📊 Updated Business Case Columns:")
print(df.columns.tolist())

# 3. Preview the "Executive" Table
df.head(3)

# Save the 'Cleaned & Renamed' version for your final report
df.to_csv("BUSIT_final_business_case.csv", index=False)

print("🏆 Your final business case file is ready for submission!")

# 1. Final check of the Business Dataset
print(f"📊 Total Teams Scraped (Rows): {len(df)}")
print(f"📋 Final Business Columns: {list(df.columns)}")
print(f"🔢 Data Types for Analysis:\n{df.dtypes}")

# 2. Executive Sample
print(f"\n📂 Executive Summary (First 5 rows):")
df.head()

# Check the 'health' of your data
print(f"✅ Data Completeness: {100 - (df.isnull().sum().sum()):.1f}%")

# 1. FINAL EXPORT: The CSV for your Business Case
df.to_csv("busit_final_output.csv", index=False)

# 2. FINAL AUDIT: Proof of Work
print(f"✅ EXPORT SUCCESSFUL")
print(f"📊 Dataset Size: {len(df)} Teams")
print(f"📋 Business Columns: {list(df.columns)}")

# 3. FINAL VISUAL: The 'Executive' Data Table
print("\n📂 Final Data Preview:")
df.head()

# 1. AUTHENTICATION (Direct and Fixed)
# Put your actual credentials inside the quotes below
SUPABASE_URL = os.environ["https://cznzegktpmjbjraotkoa.supabase.co"]
SUPABASE_KEY = os.environ["sb_publishable_tCbO7RGBmmpj4mNIdrMkug_KkNbacR0"]

# Initialize the client
try:
    supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
    print("✅ Client initialized successfully!")
except Exception as e:
    print(f"❌ Initialization failed: {e}")

# 1. PREPARE THE DATA BATCH
scrape_time = datetime.now().isoformat()
rows_to_insert = []

for _, row in df.iterrows():
    rows_to_insert.append({
        "team_identity":       str(row.get("team_identity", "Unknown")),
        "fiscal_year":         str(row.get("fiscal_year", "N/A")),
        "total_wins":          int(row.get("total_wins", 0)),
        "total_losses":         int(row.get("total_losses", 0)),
        "win_performance_kpi": float(row.get("win_performance_kpi", 0.0)),
        "scraped_at":          scrape_time,
    })

# 2. EXECUTE WITH FEEDBACK
try:
    # IMPORTANT: Ensure "hockey_analytics" is the EXACT name in your Supabase dashboard
    response = supabase.table("hockey_analytics").insert(
        rows_to_insert).execute()

    # Check if the response actually contains data
    if len(response.data) > 0:
        print(
            f"🚀 SUCCESS! {len(response.data)} rows are now LIVE in Supabase.")
    else:
        print("⚠️ The request sent, but 0 rows were added. Check your RLS policies.")

except Exception as e:
    print(f"❌ DATABASE REJECTED DATA: {e}")

# 1. Add a performance tier for dashboard grouping
# Thresholds: Below 0.45 = Underperforming, 0.45-0.55 = Competitive, Above 0.55 = Market Leader
df["performance_tier"] = df["win_performance_kpi"].apply(
    lambda kpi: "Underperforming" if kpi < 0.45
    else ("Competitive" if kpi <= 0.55 else "Market Leader")
)

# 2. Check the output (Same as your template)
print(df[["team_identity", "win_performance_kpi", "performance_tier"]].head(10))

# 3. Export the final version for Looker Studio
df.to_csv("busit_final_with_tiers.csv", index=False)

# 1. Create a lookup dictionary: Performance Category → Strategic Score
# In a business case, this represents "Resource Priority"
priority_map = {
    "Underperforming": 1,  # Low priority / Needs Review
    "Competitive": 2,      # Maintain status
    "Market Leader": 3      # High priority / Growth focus
}

# 2. .map() replaces each category with its numeric rank
# "Market Leader" becomes 3, "Underperforming" becomes 1, etc.
df["priority_score"] = df["performance_tier"].map(priority_map)

# 3. View the mapping to ensure integrity (same as your template)
print(df[["team_identity", "performance_tier", "priority_score"]].head(10))

# 4. Save the finalized file
df.to_csv("busit_final_mapped.csv", index=False)

# 1. SEGMENTATION: Identify teams in the "New York" market
# This is exactly like your "In stock" check
df["is_new_york"] = df["team_identity"].str.contains("New York", na=False)

# 2. AUDIT: See the count of New York vs. Non-New York units
print("--- Market Presence: New York ---")
print(df["is_new_york"].value_counts())

# 3. PREVIEW: See the performance of this specific segment
print("\n📂 New York Market Portfolio:")
print(df[df["is_new_york"]][["team_identity", "win_performance_kpi"]])

# 1. CLEAN-UP: Drop columns that are no longer needed for the final report
# We keep 'win_performance_kpi' but we might drop raw strings or temp columns
columns_to_drop = ["raw_scraped_text", "temp_index", "Unnamed: 0"]

df = df.drop(columns=columns_to_drop, errors="ignore")

# 2. VERIFY: Show the final professional column list
print("📋 Final Business-Ready Columns:")
print(df.columns.tolist())

# 3. EXPORT: Save the absolute final version
df.to_csv("busit_final_production.csv", index=False)

# 1. Prepare the final data batch
rows_to_insert = []
scrape_time = datetime.now().isoformat()

for _, row in df.iterrows():
    rows_to_insert.append({
        "team_identity":       str(row.get("team_identity", "Unknown")),
        "win_performance_kpi": float(row.get("win_performance_kpi", 0.0)),
        "performance_tier":    str(row.get("performance_tier", "N/A")),
        "priority_score":      int(row.get("priority_score", 0)),
        "is_new_york":         bool(row.get("is_new_york", False)),
        "scraped_at":          scrape_time
    })

# 2. Push to Supabase
try:
    # Use the table name you created earlier
    result = supabase.table("hockey_analytics").insert(
        rows_to_insert).execute()
    print(
        f"🚀 SUCCESS: {len(rows_to_insert)} rows with full business tiers are now in Supabase!")
except Exception as e:
    print(f"❌ Error: {e}")
